run:
  tests: false
  skip-dirs:
    - test
    - diagrams
  go: '1.19'

  govet:
    # Enable analyzers by name (in addition to default).
    # Run `go tool vet help` to see all analyzers.
    # Default: []
    enable:
      - fieldalignment

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - exportloopref
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - nolintlint
    - asciicheck
    # - whitespace
    # - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - linters:
        - lll
      source: "https://"
  max-same-issues: 50

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  revive:
    # Sets the default failure confidence.
    # This means that linting errors with less than 0.8 confidence will be ignored.
    # Default: 0.8
    confidence: 0
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    # Disable to ensure that nolint directives don't have a leading space. Default is true.
    allow-leading-space: true
    require-explanation: false
    require-specific: false
